export { default as NativeTemplate } from '@/forms/purchase-book-payments/NativeTemplate.vue'
export { default as Erc20Template } from '@/forms/purchase-book-payments/Erc20Template.vue'
export { default as VoucherTemplate } from '@/forms/purchase-book-payments/VoucherTemplate.vue'
export { default as NftTemplate } from '@/forms/purchase-book-payments/NftTemplate.vue'
export { default as PromocodeTemplate } from '@/forms/purchase-book-payments/PromocodeTemplate.vue'
export { default as RarimoTemplate } from '@/forms/purchase-book-payments/RarimoTemplate.vue'
