export { default as FAQGuides } from '@/pages/FAQ/FAQGuides.vue'
export { default as FAQGuidesSwitcher } from '@/pages/FAQ/FAQGuidesSwitcher.vue'
export { default as FAQGuideItem } from '@/pages/FAQ/FAQGuideItem.vue'
export { default as FAQCardInfo } from '@/pages/FAQ/FAQCardInfo.vue'
export { default as FAQMetamask } from '@/pages/FAQ/FAQMetamask.vue'
