export { default as FaqGuides } from '@/pages/faq/FaqGuides.vue'
export { default as FaqGuidesSwitcher } from '@/pages/faq/FaqGuidesSwitcher.vue'
export { default as FaqGuideItem } from '@/pages/faq/FaqGuideItem.vue'
export { default as FaqCardInfo } from '@/pages/faq/FaqCardInfo.vue'
export { default as FaqMetamask } from '@/pages/faq/FaqMetamask.vue'
export { default as FaqBuyBook } from '@/pages/faq/FaqBuyBook.vue'
export { default as FaqMobileVersion } from '@/pages/faq/FaqMobileVersion.vue'
export { default as FaqSolveProblems } from '@/pages/faq/FaqSolveProblems.vue'
